Models/LendRequest.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System;
namespace LibraryManagmentSystem.Models
{
    public class LendRequest
    {
        [Key]
        public int LendId { get; set; }
        public string LendStatus { get; set; }
        public DateTime LendDate { get; set; }
        public DateTime ReturnDate { get; set; }
        public int UserId { get; set; }
        [ForeignKey("UserId")]
        public AccountsInfo AccountsInfo { get; set; }
        public int BookId { get; set; }
        [ForeignKey("BookId")]
        public BooksInfo BooksInfo { get; set; }
        public double? FineAmount { get; set; }

    }
}

Controllers/BooksController.cs
using Microsoft.AspNetCore.Mvc;
using LibraryManagmentSystem.Models;
using System.Threading.Tasks;
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;


namespace LibraryManagmentSystem.Controllers
{
    public class BooksController : Controller
    {
        private readonly IBooksRepository _booksRepository;
        private readonly IAuthorRepository _authorRepository;
        private readonly IPublisherRepository _publisherRepository;
        private readonly LibraryManagementContext _context;
        public BooksController(IBooksRepository booksRepository, IAuthorRepository authorRepository,IPublisherRepository publisherRepository, LibraryManagementContext context)
        {
            _booksRepository = booksRepository;
            _authorRepository = authorRepository;
            _publisherRepository = publisherRepository;
            _context = context;
        }
        public IActionResult AllBooksList()
        {
            return View(_booksRepository.GetAllBooks);
        }
        public IActionResult Error()
        {
            return View(new ErrorViewModel { IsBookAvailable = false });
        }
        public async Task<IActionResult> Search(string SearchString)
        {
            var books = from b in _context.Books
                        select b;
            

            if (!String.IsNullOrEmpty(SearchString))
            {
                books = books.Where(s => s.BookTitle.Contains(SearchString) || s.AuthorInfo.AuthorName.Contains(SearchString) || s.Category.Contains(SearchString));
                
            }

            return View(await books.ToListAsync());
        }
    }
}

Controllers/LendRequestController.cs
using Microsoft.AspNetCore.Mvc;
using LibraryManagmentSystem.Models;
using System.Linq;
using System;
using Microsoft.AspNetCore.Http;
using Microsoft.Data.SqlClient;

namespace LibraryManagmentSystem.Controllers
{
    public class LendRequestController : Controller
    {
        private readonly ILendRequestRepository _lendRequestRepository;
        private readonly IBooksRepository _booksRepository;
        private readonly IAccountsRepository _accountsRepository;
        private readonly LibraryManagementContext _libraryManagementContext;

        public LendRequestController(ILendRequestRepository lendRequestRepository, LibraryManagementContext libraryManagementContext, IBooksRepository booksRepository, IAccountsRepository accountsRepository  )
        {
            _lendRequestRepository = lendRequestRepository;
            _libraryManagementContext = libraryManagementContext;
            _booksRepository = booksRepository;
            _accountsRepository = accountsRepository;   
        }


        public IActionResult AllLendRequest()
        {
            if (TempData["Message"] != null)
                ViewBag.MessageStatus = TempData["Message"].ToString();

            return View(_lendRequestRepository.GetAllLendRequest);
        }
       
        public IActionResult LendRequestById()
        {
            var username = HttpContext.Session.GetString("username");
            var user = _accountsRepository.GetUserbyName(username);
            var request = _lendRequestRepository.GetlendRequestbyId(user.UserId);
            if(request == null)
            {
                return NotFound();
            }
            return View(request);
        }
        public ViewResult RequestToLend(int bookId)
        {
            var username = HttpContext.Session.GetString("username");
            var user = _accountsRepository.GetUserbyName(username);
            LendRequest lendRequest = new LendRequest
            {
                LendStatus = "Requested",
                UserId = user.UserId,
                BookId = bookId,
                LendDate = System.DateTime.MinValue,
                AccountsInfo = _libraryManagementContext.Accounts.SingleOrDefault(u => u.UserId == user.UserId),
                BooksInfo = _libraryManagementContext.Books.SingleOrDefault(b=>b.BookId == bookId)
            }; 

            _libraryManagementContext.LendRequests.Add(lendRequest);
            _libraryManagementContext.SaveChanges();
            return View("Requested");
        }
        public RedirectToActionResult Approval(int lendId) 
        {
            LendRequest lendRequest = _lendRequestRepository.GetLendRequestByLendId(lendId);
            lendRequest.LendStatus = "Approved";
            lendRequest.LendDate = DateTime.Now;
            System.DateTime Date = DateTime.Now;
            lendRequest.BooksInfo.IssuedBooks++;
            lendRequest.ReturnDate = Date.AddDays(15);
           
            _libraryManagementContext.SaveChanges();
            ViewData["Message"] = "Request Approved !!!";
            return RedirectToAction("AllLendRequest");
        }
        public RedirectToActionResult Decline(int lendId)
        {
            LendRequest lendRequest = _lendRequestRepository.GetLendRequestByLendId(lendId);
            lendRequest.LendStatus = "Declined";
            lendRequest.LendDate = DateTime.Now;
            lendRequest.ReturnDate = DateTime.Now;
            _libraryManagementContext.SaveChanges();
            ViewData["Message"] = "Request Declined !!!";
            return RedirectToAction("AllLendRequest");
        }
        public IActionResult ReturnView()
        {
            var username = HttpContext.Session.GetString("username");
            var user = _accountsRepository.GetUserbyName(username);
            int Userid = user.UserId;
            var request = _lendRequestRepository.GetlendRequestbyId(Userid).Where(l => l.LendStatus == "Approved"  );
            
             if (request == null)
            {
                return NotFound();
            }
            return View(request);
        }
        public ViewResult ReturnBook(int lendId)
        {

            LendRequest lendRequest = _lendRequestRepository.GetLendRequestByLendId(lendId);
            lendRequest.LendStatus = "Returned";
            lendRequest.BooksInfo.IssuedBooks--;            
            DateTime date = DateTime.Now;
            int diff = (int)(date.CompareTo(lendRequest.ReturnDate));
            lendRequest.FineAmount = diff * 10;
            _libraryManagementContext.SaveChanges();
            ViewData["Message"] = "Book Returned";
            
             
             
             
                         
            /*DateTime date = DateTime.UtcNow;
            string connect;
            SqlConnection cnn;

            connect = "Server=localhost;Database=LMSdb;Trusted_Connection=True";

            cnn = new SqlConnection(connect);

            cnn.Open();

            SqlCommand command;
            SqlDataAdapter adapter = new SqlDataAdapter();
            string sql;
            DateTime output;

            sql = $"Select LendDate From LendRequests Where LendId={lendId}";
            command = new SqlCommand(sql, cnn);

            output = (DateTime)command.ExecuteScalar();
            command.Dispose();

            int diff = ((int)(date - output).TotalDays) +1;
            float fine = diff * 10;

            sql = $"Insert FineAmount={fine} into LendRequests  where LendId={lendId}";

            command = new SqlCommand(sql, cnn);

            adapter.UpdateCommand = new SqlCommand(sql, cnn);
            adapter.UpdateCommand.ExecuteNonQuery();
            command.Dispose();

            cnn.Close();*/

            return View();
        }
        public IActionResult AllPastBooks()
        {
            var request = _lendRequestRepository.GetPastRecord;
            if (request == null)
            {
                return NotFound();
            }
            return View(request);
        }
        public IActionResult LentList()
        {

            var lendList = _lendRequestRepository.GetAllApprovedBooksList;

            if (lendList == null)
            {
                return NotFound();
            }
            return View(lendList);
        }

    }
}

Views/LendRequest/AllLendRequest.cshtml
@model IEnumerable<LibraryManagmentSystem.Models.LendRequest>
 <div class="container">
  <div class="row justify-content-md-center"> 
<div class="col-md-12">
    <div class="card">
        <div class="card-body">
                  <div class="row">
                     <div class="col">
                        <center>
                           <h4>Admin's Requested Log</h4>
                        </center>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col">
                        <center>
                           <img width="100px" src="~/Images/imgs/books.png" />
                        </center>
                     </div>
                  </div>
                  
                  @if(ViewBag.MessageStatus == "Request Approved"){
                      <div class="alert alert-success alert-dismissible fade show" role="alert">
                          <strong>@ViewBag.MessageStatus</strong>
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                    }
                    else if(ViewBag.MessageStatus == "Declined")
                    {
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                          <strong>@ViewBag.MessageStatus</strong> 
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                    }

                        <div class="row">
                     <div class="col">
                        <hr>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col">
                        <table class="table table-striped table-bordered" >
                            <thead> 
                                <tr>
                                <td>Lend Id </td>
                                <td>User Name </td>
                                <td>Book Name</td>
                                <td>Status</td>
                                <td colspan="2"></td>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var request in Model)
                                {
                                    <tr>
                                        <td>@request.LendId</td>
                                        <td>@request.AccountsInfo.UserName</td>
                                        <td>@request.BooksInfo.BookTitle</td>
                                        <td>@request.LendStatus</td>
                                        <td>
                                            <form asp-controller="LendRequest" asp-action="Approval" asp-route-lendId="@request.LendId">
                                            <button>Approve</button>
                                            </form>
                                        </td>
                                        <td>
                                            <form asp-controller="LendRequest" asp-action="Decline" asp-route-lendId="@request.LendId">
                                            <button>Decline</button>
                                            </form>
                                        </td>
                                    </tr>
                                }
                        </tbody>
                        </table>
                     </div>
                  </div>
        </div>
    </div>
</div>
</div>
</div>

Views/LendRequest/AllPastBooks.cshtml
@model IEnumerable<LibraryManagmentSystem.Models.LendRequest>
 <div class="container">
  <div class="row justify-content-md-center"> 
<div class="col-md-12">
    <div class="card">
        <div class="card-body">
                  <div class="row">
                     <div class="col">
                        <center>
                           <h4> Returned and Declined Book List </h4>
                        </center>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col">
                        <center>
                           <img width="100px" src="~/Images/imgs/books.png" />
                        </center>
                     </div>
                  </div>
                        <div class="row">
                     <div class="col">
                        <hr>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col">
                        <table class="table table-striped table-bordered" >
                            <thead>
                                <tr>
                                <td>Lend Id </td>
                                <td>User Name</td>
                                <td>Book Name</td>
                                <td>Due date</td>
                                <td>Return Date</td>
                                <td>Fine Amount</td>
                                <!--<td>Status</td>-->
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var list in Model)
                                {
                                    <tr>
                                        <td>@list.LendId</td>
                                        <td>@list.AccountsInfo.UserName</td>
                                        <td>@list.BooksInfo.BookTitle</td>
                                        <td>@list.LendDate.AddDays(15)</td>
                                        <td>@list.ReturnDate</td>
                                        <td>@list.FineAmount</td>
                                        <!--
                                            
                                        </td>-->
                                     </tr>
                                }  
                        </tbody>
                        </table>
                     </div>
                  </div>
        </div>
    </div>
</div>
</div>
</div>

Views/LendRequest/LendRequestById.cshtml
@{
	Layout="_userLayout";
}
@model IEnumerable<LibraryManagmentSystem.Models.LendRequest>

 <div class="container">
  <div class="row justify-content-md-center"> 
<div class="col-md-12">
    <div class="card">
        <div class="card-body">
                  <div class="row">
                     <div class="col">
                        <center>
                           <h4>Your all records</h4>
                        </center>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col">
                        <center>
                           <img width="100px" src="~/Images/imgs/books.png" />
                        </center>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col">
                        <hr>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col">
                        <table class="table table-striped table-bordered" >
                            <thead>

                                <tr>
                                    <td>Lend Id </td>
                                    <td>User Name </td>
                                    <td>Book Name</td>
                                    <td>Fine Amount</td>
                                    <td>Status</td>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var request in Model)
                                {
                                    <tr>
                                        <td>@request.LendId</td>
                                        <td>@request.AccountsInfo.UserName</td>
                                        <td>@request.BooksInfo.BookTitle</td>
                                        <td> @request.FineAmount</td>
                                        <td>@request.LendStatus</td>
                                    </tr>
                                }
                        </tbody>
                        </table>
                     </div>
                  </div>
        </div>
    </div>
</div>
</div>
</div>

Views/LendRequest/LentList.cshtml
@model IEnumerable<LibraryManagmentSystem.Models.LendRequest>
 <div class="container">
  <div class="row justify-content-md-center"> 
<div class="col-md-12">
    <div class="card">
        <div class="card-body">
                  <div class="row">
                     <div class="col">
                        <center>
                           <h4>Lended Books List</h4>
                        </center>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col">
                        <center>
                           <img width="100px" src="~/Images/imgs/books.png" />
                        </center>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col">
                        <hr>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col">
                        <table class="table table-striped table-bordered" >
                            <thead>
                                <tr>
                                <td>Lend Id </td>
                                <td>User Name </td>
                                <td>Book Name</td>
                                <td>Lend Date</td>
                                <td>Due Date</td>
                                <td>Status</td>
                                <td colspan="2"></td>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var lendList in Model)
                                {
                                    <tr>
                                        <td>@lendList.LendId</td>
                                        <td>@lendList.AccountsInfo.UserName</td>
                                        <td>@lendList.BooksInfo.BookTitle</td>
                                        <td>@lendList.LendDate</td>
                                        <td>@lendList.ReturnDate</td>
                                        <td>@lendList.LendStatus</td>
                                     
                                    </tr>
                                }
                        </tbody>
                        </table>
                     </div>
                  </div>
        </div>
    </div>
</div>
</div>
</div>

Views/LendRequest/Requested.cshtml
@{
	Layout="_userLayout";
}
<style>
	html{
		margin: 50px;
    padding: 50px;
   
    
	}
	a,h1,h3{
		color: #531f00;
		text-decoration: none;
	}
</style>
<center>
    <h3>Your Book has been requested <br/>
    View your <a asp-controller="LendRequest" asp-action="LendRequestById" asp-route-Userid=1>requests.</a><br />
	<a asp-controller="Books" asp-action="AllBooksList">Or browse more books.</a></h3></h3>
</center>

Views/LendRequest/ReturnBook.cshtml
@{
	Layout="_userLayout";
}
@model LibraryManagmentSystem.Models.LendRequest
 <div class="container">
  <div class="row justify-content-md-center"> 
<div class="col-md-12">
    <div class="card">
        <div class="card-body">
                  <div class="row">
                     <div class="col">
                        <center>
                           <h4> Book Returned...!!! </h4>
                           
                                
                        </center>
                     </div>
                  </div>   
        </div>
    </div>
</div>
</div>
</div>

Views/LendRequest/ReturnView.cshtml
@{
	Layout="_userLayout";
}
@model IEnumerable<LibraryManagmentSystem.Models.LendRequest>
 <div class="container">
  <div class="row justify-content-md-center"> 
<div class="col-md-12">
    <div class="card">
        <div class="card-body">
                  <div class="row">
                     <div class="col">
                        <center>
                           <h4> Your Issued Books </h4>
                        </center>
                     </div>
                  </div>
                    <div class="row">
                     <div class="col">
                        <center>
                           <img width="100px" src="~/Images/imgs/books.png" />
                        </center>
                     </div>
                  </div>
                        <div class="row">
                     <div class="col">
                        <hr>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col">
                        <table class="table table-striped table-bordered" >
                            <thead>
                                <tr>
                                <td>Lend Id </td>
                                <td>Book Name</td>
                                <td>Lend Date</td>
                                <td>Due Date</td>
                                <td>Status</td>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var list in Model)
                                {
                                    <tr>
                                        <td>@list.LendId</td>
                                        <td>@list.BooksInfo.BookTitle</td>
                                        <td>@list.LendDate</td>
                                        <td>@list.ReturnDate</td>
                                        
                                        <td>
                                        @if(list.LendStatus == "Approved"){
                                           
                                            <form asp-controller="LendRequest" asp-action="ReturnBook" asp-route-lendId="@list.LendId">
                                            <button>Return Book</button>
                                            </form>
                                            }
                                            else
                                            {
                                               @list.LendStatus
                                            }
                                        </td>
                                     </tr>
                                }
                                

                                     
                        </tbody>
                        </table>
                     </div>
                  </div>
        </div>
    </div>
</div>
</div>
</div>